[tool.poetry]
name = "redis-inbound-outbound-services"
version = "0.1.0"
description = "ACA-Py Redis HTTP and WS inbound/outbound services"
authors = ["Shaanjot Gill <gill.shaanjots@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
redis = "^5.0.6"
aiohttp = "^3.9.5"
fastapi-slim = "^0.111.1"
uvicorn = "^0.29.0"
nest-asyncio = "^1.5.5"
pydantic = "^1.10.15"

[tool.poetry.dev-dependencies]
black = "~24.4.2"
flake8 = "^3.9.1"
pre-commit = "^2.12.1"
pydantic = "^1.10.15"
pytest = "^8.2.0"
pytest-cov = "^5.0.0"
pytest-asyncio = "~0.23.7"
rope = "^1.13.0"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"