label: webvh-author

auto-provision: true

admin: [0.0.0.0, 4001]
admin-insecure-mode: true

inbound-transport:
  - [http, 0.0.0.0, 4000]
  - [ws, 0.0.0.0, 4002]
outbound-transport: http
endpoint:
  - http://localhost:4000

plugin:
  - webvh

no-ledger: true

# Wallet
wallet-type: askar-anoncreds
wallet-name: author-wallet
wallet-key: insecure


log-level: info

auto-accept-invites: true
auto-respond-messages: true

# Plugin
plugin-config-value:
plugin-config-value:
  - did-webvh.server_url=https://localhost:8000
  - did-webvh.role=author
  - did-webvh.endorser_invitation=http://localhost:3000?oob=eyJAdHlwZSI6ICJodHRwczovL2RpZGNvbW0ub3JnL291dC1vZi1iYW5kLzEuMS9pbnZpdGF0aW9uIiwgIkBpZCI6ICJmOWEyZWMyMC03NWUwLTQzMWMtYTJiMi03ZjEzYmJlNmE1OTUiLCAibGFiZWwiOiAid2VidmgtZW5kb3JzZXIiLCAiaGFuZHNoYWtlX3Byb3RvY29scyI6IFsiaHR0cHM6Ly9kaWRjb21tLm9yZy9kaWRleGNoYW5nZS8xLjAiXSwgInNlcnZpY2VzIjogW3siaWQiOiAiI2lubGluZSIsICJ0eXBlIjogImRpZC1jb21tdW5pY2F0aW9uIiwgInJlY2lwaWVudEtleXMiOiBbImRpZDprZXk6ejZNa25lSDlibmlxRlptZ2hUSEh3cVpyVll2OFV6TEdvQzNEOFg3dVNydE05NnJUI3o2TWtuZUg5Ym5pcUZabWdoVEhId3FaclZZdjhVekxHb0MzRDhYN3VTcnRNOTZyVCJdLCAic2VydmljZUVuZHBvaW50IjogImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9XX0